"""empty message

Revision ID: fcdf747baa43
Revises: e76ab6903800
Create Date: 2023-11-27 10:26:54.098756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdf747baa43'
down_revision = 'e76ab6903800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edit_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_edit_timestamp'), ['edit_timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_edit_timestamp'))
        batch_op.drop_column('edit_timestamp')

    # ### end Alembic commands ###
